swagger: '2.0'
info:
  title: Perun API
  description: Perun API for providers
  version: 1.0.0
basePath: /v1
schemes:
  - http
paths:
  /provider/register:
    post:
      summary: Register a new provider
      description: Registers a provider if it is reachable via gRPC at provided host and port
      operationId: RegisterProvider
      parameters:
        - in: body
          description: Provider's gRPC server's host and port
          name: host
          schema:
            $ref: '#/definitions/Host'
          required: true

      responses:
        200:
          description: Provider successfully registered
        403:
          description: Failed to confirm provider reachability

definitions:
  Host:
    type: object
    properties:
      host:
        type: string
      port:
        type: integer
        default: 9002
    required:
      - host
