// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sithell/perun/api/models"
)

// CreateJobOKCode is the HTTP code returned for type CreateJobOK
const CreateJobOKCode int = 200

/*
CreateJobOK Job successfully registered

swagger:response createJobOK
*/
type CreateJobOK struct {

	/*
	  In: Body
	*/
	Payload *models.Job `json:"body,omitempty"`
}

// NewCreateJobOK creates CreateJobOK with default headers values
func NewCreateJobOK() *CreateJobOK {

	return &CreateJobOK{}
}

// WithPayload adds the payload to the create job o k response
func (o *CreateJobOK) WithPayload(payload *models.Job) *CreateJobOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create job o k response
func (o *CreateJobOK) SetPayload(payload *models.Job) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateJobOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
