// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sithell/perun/api/models"
)

// GetJobByIDOKCode is the HTTP code returned for type GetJobByIDOK
const GetJobByIDOKCode int = 200

/*
GetJobByIDOK Successfully fetched job

swagger:response getJobByIdOK
*/
type GetJobByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Job `json:"body,omitempty"`
}

// NewGetJobByIDOK creates GetJobByIDOK with default headers values
func NewGetJobByIDOK() *GetJobByIDOK {

	return &GetJobByIDOK{}
}

// WithPayload adds the payload to the get job by Id o k response
func (o *GetJobByIDOK) WithPayload(payload *models.Job) *GetJobByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get job by Id o k response
func (o *GetJobByIDOK) SetPayload(payload *models.Job) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJobByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
